### ISSUE TITLE
How do i resolve this error?

### ISSUE THREAD

**Issue by knightcube** [2d-inc/HistoryOfEverything#41]
Logs:
`error: Invalid override. The type of 'AmeliaController.initialize' ('(FlutterActorArtboard) → void') isn't a subtype of 'FlareInteractionController.initialize' ('(dynamic) → void'). (strong_mode_invalid_method_override at [timeline] lib\article\controllers\amelia_controller.dart:24)`

**Comment by luigi-rosso** [comment]
Could you post the log from your flutter doctor? Make sure you're on the latest version of flutter and are using the same pubspec.yaml that's provided in this repository.
