### ISSUE TITLE
Error running Gradle

### ISSUE THREAD

**Issue by sagardesai90** [2d-inc/HistoryOfEverything#43]
I ran the commands in the readme below but came across an error with running Gradle.
Startup commands:
```
git clone https://github.com/2d-inc/HistoryOfEverything.git
cd HistoryOfEverything/app
git submodule init
git submodule update
flutter run
```
Error:
Launching lib/main.dart on SM G935P in debug mode...
Initializing gradle...                                       1.7s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "/Users/sagardesai/Documents/Personal/Repos/HistoryOfEverything/app/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sagardesai/Documents/Personal/Repos/HistoryOfEverything/app/android/app/build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: /Users/sagardesai/Documents/Personal/Repos/HistoryOfEverything/app/android/gradlew app:properties

Please review your Gradle project setup in the android/ folder.

Any idea what could be going on?

**Comment by sagardesai90** [comment]
Never mind, I got it to work after recloning the repo!

**Comment by erluxman** [comment]
I am still getting this error..
