### ISSUE TITLE
App compiles despite presence of A lot of compiler error..

### ISSUE THREAD

**Issue by erluxman** [2d-inc/HistoryOfEverything#48]
App compiles and runs but when I want to see the code, there are a lot of compiler errors, that I can't ignore. Am I missing something? How to fix the errors?

<img width="1662" alt="screen shot 2019-01-19 at 4 22 19 pm" src="https://user-images.githubusercontent.com/6260014/51425607-99f71880-1c06-11e9-847a-3ca57a7c8bc2.png">
<img width="1630" alt="screen shot 2019-01-19 at 4 22 54 pm" src="https://user-images.githubusercontent.com/6260014/51425608-9d8a9f80-1c06-11e9-850a-eee17f47a5ee.png">

**Comment by umberto-sonnino** [comment]
That's probably because your Android project is pointing to the `HistoryOfEverything` folder instead of `HistoryOfEverything/app`

**Comment by erluxman** [comment]
You mean I should open app directory as an Android Studio/flutter project?

**Comment by erluxman** [comment]
Thanks a lot...
