### ISSUE TITLE
How can i open the files with .flr suffix  extension ?

### ISSUE THREAD

**Issue by TaurusXi** [2d-inc/HistoryOfEverything#58]
How can i open the files with .flr suffix  extension under macOS 10.14 environment ?
Anyone could show me  the function ?

**Comment by luigi-rosso** [comment]
These files are output from Flare, but they're not the Flare project files. To browse the History of Everything files on 2Dimensions.com, please visit this link: https://www.2dimensions.com/explore/tagged/historyofeverything/trending/all
