### ISSUE TITLE
error with Nima-Flutter

### ISSUE THREAD

**Issue by GuixiangCao** [2d-inc/HistoryOfEverything#62]
Error: The
argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
		_canvasVertices = new ui.Vertices.raw(ui.VertexMode.triangles, _vertexBuffer,
		indices: _indices, textureCoordinates: _uvBuffer);

**Comment by catalsdevelop** [comment]
Flutter has break changes in master/dev with stable. see https://github.com/2d-inc/Flare-Flutter/issues/79

**Comment by luigi-rosso** [comment]
Now that the Uin16List change has landed in Flutter Stable, I've pushed an update to this repository reflecting the change. I did this by updating the Flare and Nima dependencies to the latest versions.
