### ISSUE TITLE
Tried calling: color=Instance of 'Color'

### ISSUE THREAD

**Issue by superaldo** [2d-inc/HistoryOfEverything#68]
Hello,

This is my first time cloning the HistoryOfEverything I follow the steps 
git clone https://github.com/2d-inc/HistoryOfEverything.git
cd HistoryOfEverything/app
git submodule init
git submodule update
flutter run

and is working until I hit on any article to read it show this error:
I/flutter (18745): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18745): The following NoSuchMethodError was thrown building Container(constraints:
I/flutter (18745): BoxConstraints(0.0<=w<=Infinity, h=280.0)):
I/flutter (18745): The setter 'color=' was called on null.
I/flutter (18745): Receiver: null
I/flutter (18745): Tried calling: color=Instance of 'Color'
I/flutter (18745):
I/flutter (18745): User-created ancestor of the error-causing widget was:
I/flutter (18745):   GestureDetector

**Comment by luigi-rosso** [comment]
Thanks for reporting this. I'm looking into it right now.

**Comment by luigi-rosso** [comment]
Try pulling the latest version, this should be fixed now.

**Comment by superaldo** [comment]
> Try pulling the latest version, this should be fixed now.

Cool, is working now, thank you.
