### ISSUE TITLE
Can't display correctly

### ISSUE THREAD

**Issue by KernelErr** [2d-inc/HistoryOfEverything#73]
After following the usage section's steps, I got an error: resource android:attr/fontVariationSettings not found. So I changed compileSdkVersion to 28, it ran successfully. But can't display any media.
Here's some screenshots:
![Screenshot_1583043164](https://user-images.githubusercontent.com/45716019/75620698-ef9e4280-5bc6-11ea-862e-5a7b53c0e67c.png)
![Screenshot_1583043188](https://user-images.githubusercontent.com/45716019/75620699-f1680600-5bc6-11ea-93fd-ff8c5a6cc2d7.png)
Thanks for your kind reply. :)

**Comment by KernelErr** [comment]
E/flutter (10023): Unable to load asset: assets/Milky Way/Milky Way.flr
E/flutter (10023): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (10023): <asynchronous suspension>
E/flutter (10023): #1      FlutterActor.loadFromBundle (package:flare_flutter/flare.dart:662:39)
E/flutter (10023): #2      Timeline.loadFromBundle (package:timeline/timeline/timeline.dart:440:44)
E/flutter (10023): <asynchronous suspension>
E/flutter (10023): #3      new BlocProvider (package:timeline/bloc_provider.dart:28:10)
E/flutter (10023): #4      TimelineApp.build (package:timeline/main.dart:15:12)
E/flutter (10023): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
E/flutter (10023): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
E/flutter (10023): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (10023): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
E/flutter (10023): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
E/flutter (10023): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
E/flutter (10023): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (10023): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
E/flutter (10023): #13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
E/flutter (10023): #14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (10023): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter (10023): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter (10023): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by KernelErr** [comment]
That's strange. I must hot reload every time to load the assets file.

**Comment by Dilshan97** [comment]
I falling with the same issue. :-( I can't find any solution to that issue.  we can load the assets using a hot reload. but the thing is when we build release APK, it contains the same issue.
