### ISSUE TITLE
unable to run the downloaded app, even after updating to androidX

### ISSUE THREAD

**Issue by arfeenmushtaq** [2d-inc/HistoryOfEverything#88]
Hi,
  I have downloaded the code, and updated to android x

the nima & flare were not recognized pathes even after efforts, so replaced with 
nima: ^1.0.5
flare_flutter: ^2.0.6

now the application loads but I'm getting exception in file timeline.dart (#496): flareAsset.actor.advance(0.0);

please upload bug free project 

![error_timeline](https://user-images.githubusercontent.com/16346106/94018046-90558900-fdc9-11ea-9aac-d1b801b29c66.PNG)

**Comment by silentsile** [comment]
Sorry what is this for?

**Comment by arfeenmushtaq** [comment]
There is error in the dependencies in Nima flutter

**Comment by arfeenmushtaq** [comment]
resolved the issue, seems like Nima & Flare must be separately downloaded and them pub get for the app to work
